---
- name: "Create folder"
  ansible.builtin.file:
    path: "/app/"
    owner: root
    group: root
    mode: '0777'
    state: directory

- name: "Copy app"
  ansible.builtin.copy:
    src: "files/xpaste/"
    dest: "/app/"
    owner: "root"
    group: "root"
    mode: '0777'

- name: "Config build.nokogiri"
  ansible.builtin.shell: "source /opt/rh/rh-ruby25/enable && bundle config build.nokogiri --use-system-libraries"
  args:
    chdir: "/app/"

- name: "Install nokogiri"
  ansible.builtin.shell: "source /opt/rh/rh-ruby25/enable && gem install nokogiri:1.8.2"
  args:
    chdir: "/app/"

- name: "libfix"
  ansible.builtin.shell: "source /opt/rh/rh-ruby25/enable && gem install bundler:1.16.2"
  args:
    chdir: "/app/"

- name: "Install app"
  ansible.builtin.shell: "source /opt/rh/rh-ruby25/enable && bundle install --clean --no-cache --without development"
  args:
    chdir: "/app/"
  ignore_errors: yes

- name: "xpaste service file"
  template:
    src: "service.j2"
    dest: "/etc/systemd/system/xpaste.service" 
    owner: root
    group: root 
    mode: 0664

- name: "Start service"
  ansible.builtin.service:
    name: xpaste
    state: started
